# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'SamplePOCMVVM' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SamplePOCMVVM
    pod 'Alamofire', '~> 5.1'
    pod 'SDWebImage', '~> 5.0'
    pod 'SnapKit', '~> 5.0'
    pod 'SwiftLint'

  target 'SamplePOCMVVMTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Alamofire', '~> 5.1'
    pod 'SDWebImage', '~> 5.0'
    pod 'SnapKit', '~> 5.0'
    pod 'SwiftLint'
  end
  
  target 'SamplePOCMVVMUITests' do
     inherit! :search_paths
     # Pods for testing
     pod 'Alamofire', '~> 5.1'
     pod 'SDWebImage', '~> 5.0'
     pod 'SnapKit', '~> 5.0'
     pod 'SwiftLint'
   end

end
